[package]
name = "gsquire"
version = "0.1.0"
authors = ["Jacob Kiesel <kieseljake@gmail.com>"]

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs", rev = "7d475fa" }
chrono = { version = "0.4", features = ["serde"] }
